### ISSUE TITLE
Fatal Drawing Errors

### ISSUE THREAD

**Issue by benhylak** [CS3733TeamBeta/Faulkner.Kiosk#49]
Having trouble switching inbetween floors. Nodes default to upper left corners, sometimes don't show up, etc. Mostly due to our somewhat sketchy loading process... Will work on this ASAP

**Comment by pjpolley** [comment]
I am also looking through this. Hopefully one of us can fix the problems here soon.

**Comment by benhylak** [comment]
I'm currently revamping the loading process.

**Comment by benhylak** [comment]
*rendering

**Comment by bdknox** [comment]
should be all set now, but I will let Ben confirm this when he wakes up
