### ISSUE TITLE
Database is not populating Kiosk table

### ISSUE THREAD

**Issue by benhylak** [CS3733TeamBeta/Faulkner.Kiosk#94]
Upon exit, kiosk drop down is empty.

Could also not be a database problem, but for whatever reason they're cleared 

Brandon, take a first stab at this

**Comment by bdknox** [comment]
I probably just need to push my code. I'll be right there.

**Comment by bdknox** [comment]
Working on mine...just trying to figure out issue after merging in Joan's branch before I push to Develop.
