### ISSUE TITLE
Deleting Kiosk node sometimes causes fatal error

### ISSUE THREAD

**Issue by benhylak** [CS3733TeamBeta/Faulkner.Kiosk#96]
Exception:

Caused by: ERROR 23503: DELETE on table 'NODE' caused a violation of foreign key constraint 'EDGE_NODE_NODE_ID_FKA' for key (9434dcfb-9505-4ac8-aefc-a6a450444487).  The statement has been rolled back.
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.impl.sql.execute.ReferencedKeyRIChecker.doCheck(Unknown Source)
	at org.apache.derby.impl.sql.execute.RISetChecker.doPKCheck(Unknown Source)

**Comment by iancj97** [comment]
This then causes the delete button for the kiosk node to be permanently stuck on the screen.

**Comment by iancj97** [comment]
[Image](https://files.slack.com/files-pri/T3R31PV1N-F4B4SEDUZ/untitled.png)

**Comment by iancj97** [comment]
If you somehow have the patience to leave this on your screen for 2 minutes without touching it, the momento pattern kicks in and resets it to the ADMIN side.

**Comment by bdknox** [comment]
if it works for you mark this as resolved, if not let me know

**Comment by iancj97** [comment]
Now nothing loads, so I can't test. When I add in nodes, then close the program, then reopen the program, all node are gone.

If I manually open the nodes in the DB, they still exists. However, if I enter admin view, see no nodes, then hit save, it saves "no nodes" and deletes all the nodes.

**Comment by bdknox** [comment]
okay well then I just need to push...Hopefully we get this issue with the controller figured out soon

**Comment by iancj97** [comment]
Are you still working on this?

**Comment by bdknox** [comment]
yes Joan just found the error...the remote repository probably works with the kiosk nodes though. Sorry some kid just unplugged our entire workbench in robotics so I was scrambling to make sure nothing got screwed up

**Comment by bdknox** [comment]
yes I'm still working on it I mean

**Comment by iancj97** [comment]
Seems to be ok if you load into Faulkner, but not Belkin.
